### ISSUE TITLE
Runtime or compile time?

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_await#1]
First of all, great works! This library looks like a very nice complement to the tink libraries. 

But looking at the readme I see the meta are `@async` and `@await`, so are they runtime transformation or not?  Because I think that compile time meta has a convention of starting with `@:`, e.g `@:async`)

**Comment by benmerckx** [comment]
There's no runtime transformation. They get stripped by the macros so there's no real need for the colon. To be exact the 'async' meta I forgot to strip in this version, but that'll get fixed next. I have thought about supporting both forms, because I've already written @:await several times by accident which is hard to debug until you notice the typo.

**Comment by kevinresol** [comment]
I think `@async` looks like a runtime thing, due to convention. Maybe just support `@:async` while produce a warning (`Context.warning()`) when a `@async` is seen.

**Comment by benmerckx** [comment]
Both forms are supported now. I kind of like writing @await instead of @:await :)

**Comment by kevinresol** [comment]
Thanks! I prefer `@:await` though, because it is more consistent with the language =)
