### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by posxposy** [haxetink/tink_await#19]
Hey ;)

With this code:
```haxe
    @:async private function someFunc(url:String):String {
        var f:FutureTrigger<String> = Future.trigger();
        MyHttp.call(url, function(data:String):Void {
            f.trigger(data);
        }, function(error:String):Void {
            f.trigger(data);
        });
        
        return f.asFuture();
    }

    function new() {
       var result:String = @await someFunc("google.com");
       trace(result);
    }
```

I got an error:
`tink.core.Future<String> should be String`

If I change it to 
```haxe
@:async private function someFunc(url:String):Future<String>
(...)
var result:Future<String> = @await someFunc("google.com");
```
then it compiles ok, but how to get my result as String and not as Future<String>?
Thanks.

**Comment by kevinresol** [comment]
did you put `@:await` on your class?

**Comment by posxposy** [comment]
Yes, I am. That did not helped.

**Comment by kevinresol** [comment]
The problem is that:

1. you should not return a Future manually in a function tagged with @:async, just return the plain type (String in your case)
2. you need to tag a function with either `@:async` or `@:await` so that its content will be transformed. In your case the constructor is not tagger so that the `@await` inside it won't do anything.

The following code should work.

```haxe
using tink.CoreApi;

@:await
class Main {
    
    function f() {
        var trigger = Future.trigger();
        trigger.trigger('hello');
        return trigger.asFuture();
    }
    
    @:await function new() {
        var s = @:await f();
        trace(s);
    }
    
    static function main() {
       new Main();
    }
}
```

**Comment by posxposy** [comment]
Ah, thank you, thats help me a lot! Got it to work now.
